version: '3'

services:
    httpd:
        image: atdock/httpd:2.4
        container_name: cidemo_httpd
        volumes:
            - "./:/usr/local/apache2/htdocs"
            - "./.docker/httpd/default.conf:/usr/local/apache2/conf.d/default.conf"
        networks:
            at_network:
                ipv4_address: 172.37.1.2
        links:
          - php

    php:
        image: atdock/php:7.1
        container_name: cidemo_php
        volumes:
            - "./:/var/www"
            - "./.docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf"
        networks:
            at_network:
                ipv4_address: 172.37.1.3

networks:
    at_network:
        ipam:
            driver: default
            config:
                - subnet: 172.37.1.0/16
